
export const TRADING_QUOTES: string[] = [
  "Trust your process, trust the plan.",
  "The market pays those who wait.",
  "A loss is just a lesson you paid for.",
  "Trade your strategy, not your feelings.",
  "One great trade is better than 100 rushed ones.",
  "Fear fades, confidence remains.",
  "Let your winners grow, and stop your losers fast.",
  "Be ready, and success will find you.",
  "Focus on doing things right, the money will follow.",
  "Your greatest skill is a calm mind.",
  "Slow and steady wins the race.",
  "Small, smart steps lead to big gains.",
  "Protect your money, and profits will come.",
  "You don't need to trade every move.",
  "A good trader waits for their moment.",
  "Skill brings confidence.",
  "A loss today makes you wiser tomorrow.",
  "You are in control of your risk.",
  "Trade to fund your life, not consume it.",
  "Discipline turns a plan into profit.",
  "The trend is your friend until it ends.",
  "Greed whispers, but discipline shouts.",
  "Your first loss is your best loss.",
  "The market doesn't care about your opinion.",
  "Price is the only truth.",
  "Plan your trade, then trade your plan.",
  "Don't force a trade that isn't there.",
  "Preserve your capital to fight another day.",
  "Review your trades, refine your edge.",
  "The goal is not to be right, but to be profitable."
];
